model_class: SHMoofModel
model_hyperparameters:
  kmer_length: 5
  site_count: 500
serialization_version: 0
site_count: 500
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.1
  min_learning_rate: 0.0001
