model_class: CNNModel
model_hyperparameters:
  dropout_rate: 0.2
  embedding_dim: 7
  filter_count: 16
  kernel_size: 9
  kmer_length: 3
serialization_version: 0
site_count: 500
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.1
  min_learning_rate: 0.0001
