model_class: CNNModel
model_hyperparameters:
  dropout_prob: 0.1
  embedding_dim: 9
  filter_count: 9
  kernel_size: 11
  kmer_length: 3
serialization_version: 0
site_count: 500
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.1
  min_learning_rate: 0.0001
