model_class: CNNModel
model_hyperparameters:
  dropout_rate: 0.0
  embedding_dim: 14
  filter_count: 25
  kernel_size: 15
  kmer_length: 3
serialization_version: 0
site_count: 500
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.1
  min_learning_rate: 0.0001
