encoder_class: KmerSequenceEncoder
encoder_parameters:
  kmer_length: 3
  site_count: 500
model_class: JoinedRSCNNModel
model_hyperparameters:
  dropout_prob: 0.0
  embedding_dim: 14
  filter_count: 25
  kernel_size: 15
  kmer_length: 3
serialization_version: 0
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.1
  min_learning_rate: 1.0e-06
