encoder_class: KmerSequenceEncoder
encoder_parameters:
  kmer_length: 5
  site_count: 500
model_class: RSSHMoofModel
model_hyperparameters:
  kmer_length: 5
  site_count: 500
serialization_version: 0
training_hyperparameters:
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.001
  min_learning_rate: 1.0e-06
