species: "human"
model_names: ["fivemer", "rsshmoof", "cnn_joi_sml", "cnn_joi_med", "cnn_joi_lrg", "cnn_joi_4k", "cnn_joi_4k_k13", "cnn_joi_8k", "cnn_hyb_sml", "cnn_hyb_med", "cnn_hyb_lrg", "cnn_hyb_4k", "cnn_hyb_4k_k13", "cnn_hyb_8k", "cnn_ind_sml", "cnn_ind_med", "cnn_ind_lrg", "cnn_ind_4k", "cnn_ind_4k_k13", "cnn_ind_8k"]
train_data_nicknames: ["shmoof_small"]
test_data_nicknames: ["shmoof_small", "tangshm"]
