species: "human"
model_names: ["fivemer", "rsshmoof", "cnn_joi_sml", "cnn_joi_med", "cnn_joi_lrg", "cnn_hyb_sml", "cnn_hyb_med", "cnn_hyb_lrg", "cnn_ind_sml", "cnn_ind_med", "cnn_ind_lrg"]
train_data_nicknames: ["shmoof_notbig"]
test_data_nicknames: ["shmoof_notbig", "val_tangshm"]
training_methods: ["simple"]
select_or_all: "all"
replicate_count: 3
min_log_prob: -4
